module:
  fofa:
    url: https://fofa.info/api/v1/search/all
    email: xxx
    token: 111111111111111111111111111
    all: true # 是否获取全部
    size: 1000 # 如果不是全部,那么最大获取多少
    batchSize: 10 # 一次查询多少
  hunter:
    url: https://hunter.qianxin.com/openApi/search
    key: 111111111111111111111111111
    all: true # 是否获取全部
    size: 1000 # 如果不是全部,那么最大获取多少
    batchSize: 5 # hunter最大支持5个拼接
  shodan:
    url: https://api.shodan.io/
    key: 111111111111111111111111111
  zone:
    url: https://0.zone/api/data/
    key: 111111111111111111111111111
    size: 10000