package utils

import (
	"gopkg.in/yaml.v3"
	"log"
	"os"
)

type AutoGenerated struct {
	Module struct {
		Fofa struct {
			URL       string `yaml:"url"`
			Email     string `yaml:"email"`
			Token     string `yaml:"token"`
			Size      int    `yaml:"size"`
			BatchSize int    `yaml:"batchSize"`
		} `yaml:"fofa"`
		Hunter struct {
			URL  string `yaml:"url"`
			Key  string `yaml:"key"`
			Size int    `yaml:"size"`
		} `yaml:"hunter"`
		Shodan struct {
			URL string `yaml:"url"`
			Key string `yaml:"key"`
		}
		Zone struct {
			URL  string `yaml:"url"`
			Key  string `yaml:"key"`
			Size int    `yaml:"size"`
		}
	} `yaml:"module"`
}

var Config *AutoGenerated

func GetConfig() *AutoGenerated {
	file, err := os.ReadFile("config.yaml")
	if err != nil {
		log.Fatal(err)
	}
	err2 := yaml.Unmarshal(file, &Config)

	if err2 != nil {
		log.Fatal(err2)
	}
	return Config
}
